from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
TMP_DIR = ROOT_DIR / "tmp"
PROGRESSION_PATH = TMP_DIR / "progression.json"

WIDTH = 240
HEIGHT = 180
SAFE_MARGIN = 8
TOP_HUD_H = 22
BOTTOM_HUD_H = 30

BASE_PADDLE_W = 24
PADDLE_H = 4
PADDLE_Y = HEIGHT - 10
PADDLE_SPEED = 3

BALL_R = 2
BASE_BALL_SPEED = 2.26

BLOCK_COLS = 8
BLOCK_ROWS = 4
BLOCK_W = 18
BLOCK_H = 6
BLOCK_GAP = 2
BLOCK_FIELD_WIDTH = BLOCK_COLS * BLOCK_W + (BLOCK_COLS - 1) * BLOCK_GAP
BLOCK_OFFSET_X = (WIDTH - BLOCK_FIELD_WIDTH) // 2
BLOCK_OFFSET_Y = TOP_HUD_H + SAFE_MARGIN + 4

ITEM_FALL_SPEED = 1
ITEM_SIZE = 5
ITEM_DURATION = 60 * 8
ITEM_BONUS_DURATION = 60 * 10
ITEM_BLOCK_COUNT = 6
HARD_BLOCK_COUNT = 5
ITEM_BLOCK_INC_PER_STAGE = 1
HARD_BLOCK_INC_PER_STAGE = 1

START_SLOW_DURATION = 60 * 3
START_SLOW_RATE = 0.5
BASE_SPEED_RATE = 0.8

FAST_BASE_RATE = 1.0
MAX_BALLS = 5
WIDE_LEVEL_MAX = 3
SLOW_LEVEL_MAX = 3
MULTI_LEVEL_MAX = 3
FAST_LEVEL_MAX = 3

MOVING_BLOCK_W = BLOCK_W
MOVING_BLOCK_H = BLOCK_H
MOVING_BLOCK_Y = BLOCK_OFFSET_Y + (BLOCK_ROWS + 1) * (BLOCK_H + BLOCK_GAP)
MOVING_BLOCK_SPEED = 0.8

START_PANEL_W = 196
START_PANEL_H = 96
START_PANEL_X = (WIDTH - START_PANEL_W) // 2
START_PANEL_Y = (HEIGHT - START_PANEL_H) // 2

START_LIVES = 3
STAGE_CLEAR_WAIT = 90

JP_FONT_PATH = str(ROOT_DIR / "assets/fonts/PixelMplus12-Regular.ttf")
JP_FONT_FALLBACK_PATH = str(ROOT_DIR / "assets/fonts/umplus_j12r.bdf")
JP_FONT_SIZE = 12
JP_SMALL_FONT_PATH = str(ROOT_DIR / "assets/fonts/umplus_j12r.bdf")
JP_FONT_SYSTEM_CANDIDATES = [
    "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
    "/usr/share/fonts/opentype/ipafont-gothic/ipag.ttf",
    "/usr/share/fonts/truetype/fonts-japanese-gothic.ttf",
]
